# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpayCo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10)),
                ('p_key', models.CharField(max_length=40)),
                ('p_currency_code', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=3)),
                ('test', models.BooleanField(default=True)),
                ('url_response', models.URLField()),
                ('url_confirmation', models.URLField()),
            ],
            options={
                'verbose_name': 'EpayCo',
                'verbose_name_plural': 'EpayCo',
            },
        ),
    ]
