# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epayco', '0001_initial'),
    ]

    def forwards_func(apps, schema_editor):
        db_alias = schema_editor.connection.alias

        EpayCo = apps.get_model('epayco', 'EpayCo')
        EpayCo.objects.using(db_alias).create(id=1)

    def reverse_func(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        EpayCo = apps.get_model('epayco', 'EpayCo')
        EpayCo.objects.using(db_alias).all().delete()

    operations = [
            migrations.RunPython(forwards_func, reverse_func)
    ]
