# Generated by Django 2.0 on 2017-12-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendgrid_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendgrid',
            options={'verbose_name': 'Sendgrid', 'verbose_name_plural': 'Sendgrid'},
        ),
    ]
